name: CD Pipeline - DigitalOcean

on:
  workflow_run:
    workflows: ["CI Pipeline"]
    branches: [main, Code-Overview]
    types: [completed]

jobs:
  deploy:
    name: Deploy to DigitalOcean
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.workflow_run.head_branch }}

      - name: Deploy to Droplet
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.DIGITALOCEAN_HOST }}
          username: ${{ secrets.DIGITALOCEAN_USERNAME }}
          key: ${{ secrets.DIGITALOCEAN_SSH_KEY }}
          passphrase: ${{ secrets.DIGITALOCEAN_SSH_PASSPHRASE }}
          script: |
            # Navigate to project directory
            cd /var/www/my-mern-app
            
            # Determine branch name from the workflow that triggered this
            BRANCH="${{ github.event.workflow_run.head_branch }}"
            
            # Clone or update repository
            if [ ! -d ".git" ]; then
              # If directory doesn't exist, clone it
              git clone https://github.com/hsinemt/Integrated-project-management-application.git .
              git checkout $BRANCH
            else
              # If directory exists, pull latest changes
              git fetch origin
              git checkout $BRANCH
              git pull origin $BRANCH
            fi
            
            # Backend deployment
            cd Back-End
            npm ci
            # Update .env file with production values
            echo "PORT=9777" > .env
            echo "MONGODB_URL=${{ secrets.MONGODB_URL }}" >> .env
            echo "NODE_ENV=production" >> .env
            # Add other environment variables
            
            # Restart the Node.js application with PM2
            pm2 restart server || pm2 start server.js --name "ipm-backend"
            
            # Frontend deployment
            cd ../Front-End
            npm ci
            npm run build
            
            # If using Nginx to serve the React app
            # Copy build files to Nginx served directory
            cp -r build/* /var/www/html/
            
            # Reload Nginx if needed
            sudo systemctl reload nginx

      - name: Verify deployment
        run: |
          echo "Deployment to DigitalOcean completed"
          # Add health check
          curl -s ${{ secrets.BACKEND_URL }}/health || echo "Health check failed but continuing"